/**
 * Each page's sections, in order. The right-hand rail draws one dot per entry
 * and search indexes the labels (plus the optional keywords), so a heading
 * added to a page belongs here too.
 */

export type Section = { id: string; label: string; keywords?: string };

export const SECTIONS: Record<string, Section[]> = {
  "/": [
    { id: "overview", label: "Overview" },
    { id: "install", label: "Install", keywords: "curl npm bun npx" },
    { id: "what-it-does", label: "What It Does" },
    { id: "grounded", label: "Grounded Answers", keywords: "citations confidence verification" },
    { id: "study", label: "Study Tools", keywords: "timeline grade quiz" },
    { id: "local-first", label: "Local First", keywords: "privacy cache offline" },
    { id: "how-it-works", label: "How It Works", keywords: "architecture" },
    { id: "next-steps", label: "Next Steps" },
  ],
  "/quickstart/": [
    { id: "before", label: "Before You Begin", keywords: "requirements token" },
    { id: "install", label: "Install" },
    { id: "token", label: "Get a Token", keywords: "access token approved integrations" },
    { id: "sign-in", label: "Sign In", keywords: "login wizard" },
    { id: "pick-courses", label: "Pick Courses" },
    { id: "course", label: "Open a Course" },
    { id: "workspace", label: "Open a Workspace", keywords: "assignment" },
    { id: "ask", label: "Ask a Question" },
    { id: "next", label: "Where Next" },
  ],
  "/installation/": [
    { id: "requirements", label: "Requirements", keywords: "node macos linux windows" },
    { id: "script", label: "Install Script", keywords: "curl install.sh binary" },
    { id: "npm", label: "npm and Others", keywords: "bun pnpm npx" },
    { id: "verify", label: "Verify" },
    { id: "update", label: "Update", keywords: "upgrade latest" },
    { id: "options", label: "Script Options", keywords: "version install dir CANVAS_CLI_INSTALL_DIR" },
    { id: "security", label: "How It's Verified", keywords: "sha256 checksum signature" },
    { id: "uninstall", label: "Uninstall", keywords: "remove" },
    { id: "source", label: "From Source", keywords: "git clone build" },
  ],
  "/shell/": [
    { id: "scopes", label: "Three Scopes", keywords: "global course workspace" },
    { id: "global", label: "Global" },
    { id: "course", label: "Course" },
    { id: "workspace", label: "Workspace" },
    { id: "moving", label: "Moving Around", keywords: "back home recent open" },
    { id: "input", label: "Typing", keywords: "keyboard shortcuts esc ctrl" },
    { id: "pins", label: "@ Pins", keywords: "attach file resource" },
    { id: "sessions", label: "Sessions", keywords: "history persist clear" },
  ],
  "/workspaces/": [
    { id: "opening", label: "Opening One" },
    { id: "preparation", label: "Preparation", keywords: "investigation work agent" },
    { id: "views", label: "Views", keywords: "overview requirements plan resources evidence status" },
    { id: "files", label: "Files", keywords: "assignment.md plan.md notes.md workup.json" },
    { id: "due-dates", label: "Due-Date Conflicts" },
    { id: "refresh", label: "Staying Current", keywords: "stale refresh" },
  ],
  "/asking-questions/": [
    { id: "loop", label: "How It Works", keywords: "agent loop steps" },
    { id: "tools", label: "Tools", keywords: "search_course read_file" },
    { id: "search", label: "Search" },
    { id: "citations", label: "Citations" },
    { id: "checks", label: "Checks", keywords: "verification confidence grounding" },
    { id: "recovery", label: "Recovery Pass" },
    { id: "tips", label: "Tips" },
  ],
  "/ingestion/": [
    { id: "running", label: "Running It", keywords: "ingest refresh" },
    { id: "captured", label: "What's Captured" },
    { id: "reference-pages", label: "Reference Pages", keywords: "quiz grading scheme calendar tools" },
    { id: "extraction", label: "Extraction", keywords: "pdf docx pptx xlsx zip" },
    { id: "hidden", label: "Hidden Content", keywords: "embeds links google docs lectures" },
    { id: "feedback", label: "Your Feedback", keywords: "grader comments rubric no-feedback" },
    { id: "json", label: "JSON Output" },
    { id: "blocked", label: "Blocked APIs", keywords: "403 files pages" },
  ],
  "/study-tools/": [
    { id: "timeline", label: "Timeline", keywords: "gantt due dates" },
    { id: "grades", label: "Grades", keywords: "grade need calculator" },
    { id: "quiz", label: "Practice Quizzes", keywords: "flashcards" },
    { id: "lectures", label: "Lectures" },
    { id: "announcements", label: "Announcements", keywords: "thread discussion" },
    { id: "browse", label: "Files and Modules" },
    { id: "open", label: "Opening Things" },
    { id: "pdf", label: "PDF Export", keywords: "latex tectonic" },
    { id: "copy", label: "Copying" },
  ],
  "/ai-providers/": [
    { id: "choosing", label: "Choosing" },
    { id: "features", label: "What Needs AI" },
    { id: "anthropic", label: "Anthropic", keywords: "claude api key" },
    { id: "openai", label: "OpenAI", keywords: "gpt api key" },
    { id: "google", label: "Google", keywords: "gemini api key" },
    { id: "bedrock", label: "AWS Bedrock" },
    { id: "subscriptions", label: "Subscriptions", keywords: "copilot codex chatgpt no api key" },
    { id: "models", label: "Models", keywords: "AI_MODEL default" },
    { id: "effort", label: "Effort", keywords: "AI_EFFORT thinking reasoning" },
    { id: "detection", label: "Auto-Detection" },
  ],
  "/configuration/": [
    { id: "where", label: "Where Things Live", keywords: "config directory xdg" },
    { id: "credentials", label: "Credentials", keywords: "keychain token secrets" },
    { id: "profiles", label: "Profiles", keywords: "multiple accounts" },
    { id: "env-file", label: ".env Files" },
    { id: "variables", label: "Variables", keywords: "environment" },
    { id: "precedence", label: "Precedence" },
    { id: "config-json", label: "config.json" },
  ],
  "/cli-reference/": [
    { id: "commands", label: "Commands" },
    { id: "login", label: "login" },
    { id: "status", label: "status" },
    { id: "ingest", label: "ingest" },
    { id: "clean", label: "clean" },
    { id: "logout", label: "logout" },
    { id: "examples", label: "examples" },
    { id: "global", label: "Global Options", keywords: "debug version" },
    { id: "exit-codes", label: "Exit Codes" },
  ],
  "/slash-commands/": [
    { id: "everywhere", label: "Everywhere" },
    { id: "global", label: "Global Scope" },
    { id: "course", label: "Course Scope" },
    { id: "workspace", label: "Workspace Scope" },
  ],
  "/local-files/": [
    { id: "layout", label: "Layout" },
    { id: "courses", label: "courses/" },
    { id: "sessions", label: "sessions/" },
    { id: "chat-sessions", label: "chat-sessions/" },
    { id: "exports", label: "exports/" },
    { id: "config", label: "Config Directory" },
    { id: "cleaning", label: "Cleaning Up", keywords: "clean delete" },
  ],
  "/privacy/": [
    { id: "no-telemetry", label: "No Telemetry" },
    { id: "stays", label: "What Stays" },
    { id: "leaves", label: "What Leaves" },
    { id: "secrets", label: "Secrets" },
    { id: "subscriptions", label: "Subscription CLIs", keywords: "copilot codex sandbox mcp" },
    { id: "debug", label: "Debug Output" },
  ],
  "/troubleshooting/": [
    { id: "doctor", label: "Run /doctor" },
    { id: "auth", label: "Sign-In Errors", keywords: "401 token expired" },
    { id: "network", label: "Network Errors", keywords: "vpn firewall" },
    { id: "courses", label: "Missing Courses" },
    { id: "ai", label: "AI Not Working", keywords: "rate limit key" },
    { id: "install", label: "Install Problems", keywords: "path command not found" },
    { id: "reset", label: "Starting Over" },
  ],
  "/changelog/": [],
};
